# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f47030815f4f006c3f28299682b4482596c377057dc10954f89405c03e0326217350f4ef6fe5154084208d61f04d4e922f13a244b0d4beb638b45489b88f3c

test:
  secret_key_base: 0dd8653026ba838e4515d90c1d5d37e5623fae7bb62401673476d8f7677fb45dbd7a39a5f6cda3896531b5382d067a0fb46defc8d928d3e73a9eb4ab11cf27ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
